name: android_jellyfin_module
description: "Android 壳工程 Flutter Module 桥接层"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  # FlutterBoost 混合开发框架
  flutter_boost:
    git:
      url: 'https://github.com/alibaba/flutter_boost.git'
      ref: 'v5.0.2'

  # Jellyfin 基础包（登录 + 媒体库共用）
  jellyfin_core:
    path: ../../packages/foundation/jellyfin_core
  jellyfin_api:
    path: ../../packages/foundation/jellyfin_api
  jellyfin_dart: 0.1.0
  jellyfin_models:
    path: ../../packages/shared/jellyfin_models
  jellyfin_ui_kit:
    path: ../../packages/shared/jellyfin_ui_kit
  # 登录模块
  jellyfin_auth:
    path: ../../packages/features/jellyfin_auth
  http: ^1.2.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.example.android_jellyfin_module
    iosBundleIdentifier: com.example.androidJellyfinModule
