name: jellyfin_music_app
description: "Jellyfin 音乐专用 App"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.2.3
  shared_preferences: ^2.2.2
  just_audio: ^0.9.42
  http: ^1.2.0
  path_provider: ^2.1.5
  jellyfin_core:
    path: ../../packages/foundation/jellyfin_core
  jellyfin_api:
    path: ../../packages/foundation/jellyfin_api
  jellyfin_dart:
    path: ../../packages/vendor/jellyfin_dart_3.8
  jellyfin_models:
    path: ../../packages/shared/jellyfin_models
  jellyfin_ui_kit:
    path: ../../packages/shared/jellyfin_ui_kit
  jellyfin_music:
    path: ../../packages/features/jellyfin_music
  jellyfin_auth:
    path: ../../packages/features/jellyfin_auth
  jellyfin_personal:
    path: ../../packages/features/jellyfin_personal

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
