name: jellyfin_music
description: 音乐业务模块 — 专辑详情、艺术家详情、音乐模型
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.32.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  cached_network_image: ^3.4.0
  palette_generator: ^0.3.3+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
