name: jellyfin_download
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  native_video_downloader:
    path: ../../plugins/native_video_downloader
  jellyfin_ui_kit:
    path: ../../shared/jellyfin_ui_kit
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
