name: rvc_flutter
description: RVC 语音转换 Flutter UI 模块
version: 0.1.0
publish_to: 'none'

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter
  rvc_sdk:
    path: ../../vendor/rvc_sdk
  # 鸿蒙适配
  just_audio:
    path: ../../ohos/fluttertpc_just_audio/just_audio
  file_picker: ^8.0.0
  path_provider:
    path: ../../ohos/path_provider/path_provider

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
