name: jellyfin_auth
description: Jellyfin 登录注册 UI 业务组件
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.9.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
